# Generated by Django 4.0.2 on 2022-03-23 19:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hub.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=9, unique=True, validators=[hub.validator.DNIValidator])),
                ('CP', models.CharField(max_length=5)),
                ('Ciutat', models.CharField(max_length=70)),
                ('Aderca', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=70, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(max_length=14, validators=[hub.validator.PhoneValidator])),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Floristeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('NIF', models.CharField(max_length=9, unique=True, validators=[hub.validator.NIFValidator])),
                ('CP', models.IntegerField()),
                ('Ciutat', models.CharField(max_length=50)),
                ('Adreca', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=70, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(max_length=14, validators=[hub.validator.PhoneValidator])),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.client')),
                ('Floristeria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.floristeria')),
            ],
            options={
                'unique_together': {('Floristeria', 'Client')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitat', models.IntegerField()),
                ('Floristeria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.floristeria')),
                ('Producte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.producte')),
            ],
            options={
                'unique_together': {('Floristeria', 'Producte')},
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitat', models.IntegerField()),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.compra')),
                ('Producte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.producte')),
            ],
            options={
                'unique_together': {('Compra', 'Producte')},
            },
        ),
    ]
